.TH ispconfig-discovery-emails 1 "2026-05-13" "0.6.0" "ISPConfig Zabbix Monitoring"
.SH NAME
ispconfig-discovery-emails \- discover ISPConfig email accounts for Zabbix LLD
.SH SYNOPSIS
.B ispconfig-discovery-emails
.SH DESCRIPTION
.B ispconfig-discovery-emails
queries the ISPConfig SOAP API and outputs all configured email accounts in
Zabbix Low-Level Discovery (LLD) JSON format.
.PP
This script is intended to be called by Zabbix Agent 2 via a UserParameter.
.SH OUTPUT
JSON object with a
.B data
array containing discovered email accounts with the following macros:
.TP
.B {#MAIL_USER_ID}
Email account ID.
.TP
.B {#EMAIL}
Full email address.
.TP
.B {#MAIL_DOMAIN_ID}
Mail domain ID.
.TP
.B {#DOMAIN}
Domain name.
.TP
.B {#QUOTA}
Mailbox quota in bytes.
.TP
.B {#USED}
Currently used space in bytes.
.SH FILES
.TP
.I /etc/ispconfig-zabbix-monitoring/config.php
Configuration file with ISPConfig API credentials.
.TP
.I /usr/lib/ispconfig-zabbix-monitoring/autodiscovery/emails.php
PHP script executed by this launcher.
.SH SEE ALSO
.BR ispconfig-key-emails (1),
.BR ispconfig-discovery-websites (1),
.BR ispconfig-discovery-mail-domains (1)
.SH AUTHOR
Spoje-NET <info@spoje.net>
