.TH ispconfig-key-mail-domains 1 "2026-05-13" "0.6.0" "ISPConfig Zabbix Monitoring"
.SH NAME
ispconfig-key-mail-domains \- retrieve ISPConfig mail domain metrics for Zabbix
.SH SYNOPSIS
.B ispconfig-key-mail-domains
.I domain_id
.I key
.SH DESCRIPTION
.B ispconfig-key-mail-domains
queries the ISPConfig SOAP API for a specific metric of an individual mail
domain. It is called by Zabbix Agent 2 for each discovered mail domain.
.SH ARGUMENTS
.TP
.I domain_id
The numeric mail domain ID (as discovered by
.BR ispconfig-discovery-mail-domains (1)).
.TP
.I key
The metric key to retrieve. Available keys:
.RS
.TP
.B active
Mail domain active status (0/1).
.TP
.B domain
Domain name.
.TP
.B server_id
Server ID.
.TP
.B mail_catchall
Catch-all email address.
.TP
.B account_count
Number of email accounts in domain.
.TP
.B total_quota
Total quota for all accounts in bytes.
.TP
.B total_used
Total used space for all accounts in bytes.
.RE
.SH FILES
.TP
.I /etc/ispconfig-zabbix-monitoring/config.php
Configuration file with ISPConfig API credentials.
.TP
.I /usr/lib/ispconfig-zabbix-monitoring/keys/mail_domains.php
PHP script executed by this launcher.
.SH SEE ALSO
.BR ispconfig-discovery-mail-domains (1),
.BR ispconfig-key-websites (1),
.BR ispconfig-key-emails (1)
.SH AUTHOR
Spoje-NET <info@spoje.net>
