.TH ispconfig-zabbix-monitoring 1 "2026-05-13" "1.0.0" "ISPConfig Zabbix Monitoring Manual"
.SH NAME
ispconfig-zabbix-monitoring \- Zabbix monitoring integration for ISPConfig
.SH SYNOPSIS
.B ispconfig-zabbix-monitoring
.RI [ options ]
.SH DESCRIPTION
.B ispconfig-zabbix-monitoring
provides autodiscovery scripts, key readers, and Zabbix templates for monitoring ISPConfig installations via Zabbix.
.SH OPTIONS
No command-line options are available; see documentation for usage details.
.SH FILES
.TP
.I /usr/lib/ispconfig-zabbix-monitoring/
Main program files and scripts.
.TP
.I /usr/share/icons/hicolor/scalable/apps/ispconfig-zabbix-monitoring.svg
Application icon.
.SH AUTHOR
Spoje-NET <info@spoje.net>
.SH HOMEPAGE
https://github.com/Spoje-NET/ispconfig-zabbix-monitoring
